language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '7'
script:
  - npm run prepare
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
